--- 
Deploy: 
  Name: MyEnvironment2
  Provider: Environment
  true: 
    Branch: master
before_build: 
  - 
    cmd: ~
before_package: 
  - 
    cmd: ~
build: 
  publish_wap: true
  verbosity: minimal
version: "1.0.{build}"